### ISSUE TITLE
Asset editor: UUID is not available in pyinstaller builds

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/community-plugins#12]
This is because pyinstaller only includes modules which are actually used by the code, and the asset editor obviously wasn't around at the time of building the release.

This has been temporarily fixed by moving the import to local scope under the generate uuid button.

**Comment by Aranuvir** [comment]
I updated my branch. On Windows uuid4.py from makeclothes will be used. I didn't test it yet on windows, but on Linux uuid4.py creates errors...

**Comment by joepal1976** [comment]
Maybe it'd be possible to re-implement the uuid algorithm in a somewhat more simplistic form? 

I'm somewhat suspicious about the license consequences of copy/pasting code from PSL. On the other hand, since we apparently do that already in makeclothes, I guess it shouldn't make things worse to do so here too. 

(the python license is here: https://docs.python.org/3/license.html )

**Comment by Aranuvir** [comment]
> I'm somewhat suspicious about the license consequences of copy/pasting code from PSL.

+1, I had abdominal pain, too, when I saw the code for the first time. Should be solved now with my new (very simple :$ ) uuid generator. Hopefully there is no "import random" issue.

**Comment by joepal1976** [comment]
Yeah, that should suffice for MH's purposes. :-)

Reading https://en.wikipedia.org/wiki/Universally_unique_identifier, I guess there's more to it than just random hex numbers, but I doubt anything in the code actually tries to interpret the UUIDs. "Yada yada"  would probably work perfectly fine as a unique identifier too.

**Comment by Aranuvir** [comment]
Actually we are using uuid version 4 ( https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29 ), where almost everything is random. I've updated the generator to obtain the form: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx ...

**Comment by Aranuvir** [comment]
Propose closing ...
