### ISSUE TITLE
No json object could be decoded

### ISSUE THREAD

**Issue by lukman06** [makehumancommunity/community-plugins#24]
hi can you help me i get this error when i call a command .

**Comment by rwbaer** [comment]
This is a bit broad.  Could you provide a step-by-step reproducible example of what you are attempting to do, the steps you took, and the expected otcome?

**Comment by lukman06** [comment]
hi,i had make a script to connect to the socket of makehuman and i get that
my application is connect  when i send a command to make human i get error
No json object could be decoded ,can you help me .

**Comment by Aranuvir** [comment]
Since this is obviously more a support request, than a bug report and the OP has finally found the makehuman forum, I'm going to close the issue...
