### ISSUE TITLE
MH_Community: Python crash in convert to IK

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/community-plugins#8]
When clicking "convert to IK" button on a collada export that has the game engine skeleton:

    Traceback (most recent call last):
      File "/home/joepal/.config/blender/2.77/scripts/addons/MH_Community/snap_on_ik_rig.py", line 47, in execute
        context.scene.ignoreIKBones = True
    AttributeError: 'Scene' object has no attribute 'ignoreIKBones'

This is blender 2.77 with latest git for community-plugins and MH.

**Comment by Palmer-JC** [comment]
Fixed
